# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_VQFRIV9pHEVS07d90JVM3Ztxc8OjDit
"""

def kasallik_tashxisi(belgi):
  if belgi == "Istima ":
     return "Parasetamol iching "
  elif belgi== "Bosh og'rig'i":
     return "Bolnol"
  elif belgi == "Tish og'rig'i":
     return "Senepar"
  elif belgi =="Gripp":
    return "Antigripp"
  elif belgi =="Diabet":
    return "Metformin"
  elif belgi=="Yuqori qon bosimi":
    return "Enap"
  elif belgi=="Oshqozon og'rig'i":
    return "Mezim"
  elif belgi =="Asabiylashish va uyqusizlik":
    return "Diazepam"
  elif belgi =="Tomoq og'rig'i":
    return "Furatsilin"
  elif belgi =="Tumov":
    return "Rinoksil"
  else:
    return "Shifokorga murojaat qiling "
belgi=input("Kasallik belgisini kiriting")
natija=kasallik_tashxisi(belgi)
print(natija)

def Televideniya_kanallari(belgi):
  if belgi == "Zo'rTV ":
     return "Uxlamaysizmi "
  elif belgi== "Sport":
     return "Sport yangiliklari"
  elif belgi == "Milliy TV":
     return "Farzandim serial"
  elif belgi =="Sevimli":
    return "Zamon"
  elif belgi =="Mahalla":
    return "Qahqaha"
  elif belgi=="Kinoteatr":
    return "Shum bola"
  elif belgi=="O'zbekiston tarixi":
    return "Dunyo bo'ylab sayohat"
  elif belgi =="Navo":
    return "Nostalgi"
  elif belgi =="Toshkent":
    return "Teletahlil"
  elif belgi =="Aqlvoy":
    return "Jahldor qushlar"
  else:
    return "Bunday kanal mavjud emas "
belgi=input("Kanallar nomini kiriting")
natija=Televideniya_kanallari(belgi)
print(natija)